### PR TITLE
Compress schema

### PR DESCRIPTION
**Pull request by WillNilges**
_That really is a lot of schema, huh?_

This moves the schema into a zip file to prevent it from registering on GitHub as code. I'm primarily doing this because...

image
Yowza.

### CODE REVIEW

**Comment by galenguyer** [comment]
Hmm, I feel like reducing usability (if I want to view the schema on the web view to quickly check something, for instance) for the sake of the nicer GitHub code thingy isn't a good trade-off. However I'm not strongly opposed to it. You should add the .sql file to the gitignore so it doesn't get accidentally committed again if someone extracts it to read it.

**Comment by WillNilges** [comment]
> Hmm, I feel like reducing usability (if I want to view the schema on the web view to quickly check something, for instance) for the sake of the nicer GitHub code thingy isn't a good trade-off. However I'm not strongly opposed to it. You should add the .sql file to the gitignore so it doesn't get accidentally committed again if someone extracts it to read it.

If I do that, will you approve? Reducing usability is a valid concern, and my only counterpoint to it is that this schema is R E A L L Y dense, I don't think anyone (anyone who is sane, anyway) is going to treat this as anything but a black box.

**Comment by galenguyer** [comment]
Yeah, makes sense. 10k lines of schema is kinda obscene

**Review by galenguyer — APPROVED** [review]
Sicko mode

**Comment by Mstrodl** [comment]
Can we gzip or something instead of zip if it's just one file?
Also, rather than keeping a binary in repo, have we considered [marking it as generated](https://github.com/github/linguist/blob/master/docs/overrides.md#generated-code)?

**Comment by WillNilges** [comment]
> Can we gzip or something instead of zip if it's just one file? Also, rather than keeping a binary in repo, have we considered [marking it as generated](https://github.com/github/linguist/blob/master/docs/overrides.md#generated-code)?
> 
> ```
> # /.gitattributes
> HACKING/proxstar-postgres/schema/large.sql linguist-generated
> ```

That might not be a bad idea. I wonder if that applies retroactively as well...

**Pull request closed without merging**
